### ISSUE TITLE
USD Plugin does not read in file paths that contain colons

### ISSUE THREAD

**Issue by morgan-cg** [dreamworksanimation/dwa_usd_plugins#5] opened 2020-03-09 20:36 UTC
Our asset management system uses files paths that contain colons in them, and it appears that the USD reader cuts off the first part of the path up to the first use of a colon. In the example output below, the full path that was used in Nuke was: /p/show:shot:sq982:s8000-shot/shot.usda

```GeoSceneGraphReader::getNodeDescriptions('shot:sq982:s8000-shot/shot.usda') error 'UsdIO: file does not exist'```

**Comment by jegstad-dwa** [comment] 2020-03-10 15:45
Hi Morgan, thanks for the feedback!

That problem is due to me attempting to replicate Nuke's Read filepath handling behavior that looks for a preceding 'foo:' as an indicator to use the 'fooReader' plugin to read the file.

You can check this out by pointing a Read node to a working image file like 'my_image.jpg' and viewing it, then making the path 'foo:my_image.jpg'. The read should error with 'Error reading from my_image.jpg; error: no plugin named "fooReader" found'.

I checked Nuke 10 & 12 and they both still support this syntax, but when I put a '/' or './' in front of 'foo:' it then ignores it and tries to resolve the full text as a path. My routine is not checking for the leading path characters and that's causing your problem:
https://github.com/dreamworksanimation/dwa_usd_plugins/blob/02b283be1460ae6d02673fbfbd513cf9303aa14b/third_party/nuke/lib/Fuser/NodeIOInterface.cpp#L65

I'll try to fix this in place as my first attempt at editing an external git repo...

Cheers,
-jonathan

**Comment by morgan-cg** [comment] 2020-03-10 19:21
Hey Jonathan, yeah that explanation makes sense, thanks for checking into this issue! I'll keep a look out for your fix and follow up with new tests then.  Thanks again!

Best,
Morgan

**Comment by jegstad-dwa** [comment] 2020-03-30 16:06
Hi guys,
I'm still a little while away from committing a bunch of changes but you can try this modification of the getTrimmedPath() in the meantime:

at: https://github.com/dreamworksanimation/dwa_usd_plugins/blob/02b283be1460ae6d02673fbfbd513cf9303aa14b/third_party/nuke/lib/Fuser/NodeIOInterface.cpp#L65
change to:
```
std::string
NodeIOInterface::getTrimmedPath(const char*  src_path,
                                std::string* ext)
{
    if (!src_path || !src_path[0])
        return empty_string;

    std::string trimmed_path;
    bool have_path_chars = false;
    const char* e = NULL;
    for (const char* s=src_path; *s; ++s)
    {
        if (*s==':' && !have_path_chars)
        {
            // ext at front:
            if (s <= src_path)
                return empty_string;
            trimmed_path = (s+1);
            if (ext != NULL)
                *ext = s;
            return trimmed_path;
        }
        else if (*s=='.')
        {
            e = (s + 1); // ext at end
            have_path_chars = true;
        }
        else if (*s=='/' || *s=='\\')
        {
            e = NULL; // reset
            have_path_chars = true;
        }
    }
    trimmed_path = src_path;
    if (ext != NULL)
        *ext = (e != NULL)?e:"";

    return trimmed_path;
}

```
This code tracks whether it's encountered './\\' characters before it returns a leading extension.
I think this should do the trick, but let me know it if gets tripped up on any other characters.

Cheers,
-jonathan

**Comment by truant-bss** [comment] 2020-03-31 18:51
Jonathan, thanks!  I had something similar set up and I was able to read our assets now.  One question about the reader.  We seem to be missing a lot of instanced geo under payloads.  Does the plugin handle instances?   I read README, but are there other caveats I should be aware of.  Thanks again!

Jake

**Comment by jegstad-dwa** [comment] 2020-03-31 19:44
Hi Jake, that's great to hear.

There's no instancing support at the moment as I've not run into it in production yet at DWA... Would you have a simple asset file as an example, or is there one in the kitchen set I can check out?

The basic idea is not hard to add but we should discuss the most efficient way of handling it in a Nuke geometry context as the current Nuke geo system doesn't offer real instancing support and we likely don't want to automatically expand all instances...

I've considered initial support for this idea by using a deferred-load Fuser Node hierarchy but should probably add a proper InstancePrimitive class.

Thoughts?

**Comment by truant-bss** [comment] 2020-03-31 22:28
Jonathan:
  Thanks for the background, I figured instancing wasn't supported since as you allude to it might quickly over-burden Nuke's 3D engine.  I'm not sure if the kitchen set has any instancing in it.  I'll take a look, and if not I'll try to create a simplified USD file to test with.  I'm still getting up to speed with USD but a UI in which to choose to activate instanceable prims would be good.  Right now the tree view of the stage ends at the payload for my scene and if I wasn't aware something should be under there, I'd assume that was the end of it.  Usdview color codes them cyan as they have the instanceable attribute set, could we get something like that in the read geo's treeview?  Then have another multi list for activating the chosen payloads?

**Comment by jegstad-dwa** [comment] 2020-03-31 22:55
> could we get something like that in the read geo's treeview?

Ha..well that's what I was hoping BlueSky could help with!  :)

When I was chatting with Andrew and Mark last year about this I mentioned that making Qt UIs is my weakest area and would really appreciate some help in that area as I'm basically a neophyte with Qt.
My hacky use of the built-in SceneView Knob was intended as a standin for a 'real' UI since Foundry doesn't offer any options and the SceneView Knob is pretty functionally weak.

It's very low on my list as the SceneView hack is at least minimally functional, so some ideas in that space would be appreciated!

Re. not seeing into the payload that may be a bug that I already fixed. If a USD Prim is not Valid my tree-walk code skips it before checking if it's loaded. Problem is that the Valid state can change after loading the Prim...
https://github.com/dreamworksanimation/dwa_usd_plugins/blob/02b283be1460ae6d02673fbfbd513cf9303aa14b/third_party/nuke/plugin/FuserUsd/FuserUsdArchiveIO.cpp#L228
and
https://github.com/dreamworksanimation/dwa_usd_plugins/blob/02b283be1460ae6d02673fbfbd513cf9303aa14b/third_party/nuke/plugin/FuserUsd/FuserUsdArchiveIO.cpp#L303

I've reworked that code quite a bit but I think if you move the IsValid() test to be underneath the prim load section that should fix it for a workaround.

**Comment by truant-bss** [comment] 2020-04-01 00:14
> Ha..well that's what I was hoping BlueSky could help with! :)

Yes of course!  Sorry, I didn't mean to imply for you to do the work.  It's very much your project so I'd want to run any requests by you first.  I will ask mgmt about how much time they will give me.  We were already swamped with a complete overhaul of our pipeline before the world got even crazier.  I'm mainly a python guy but I do have experience with PyQt, so please bear with me while I stretch my c++ legs, it's been a while.  Thank you again for that workaround for the treeview, I'll test that out in the morning.

**Comment by truant-bss** [comment] 2020-04-01 19:02
Thanks!  Moving those IsValid checks below the load allowed me to see the whole stage.  I'll continue testing now that I can load our scenes and try to get you that example of instances soon.

**Comment by truant-bss** [comment] 2020-04-01 19:19
> Thanks! Moving those IsValid checks below the load allowed me to see the whole stage. I'll continue testing now that I can load our scenes and try to get you that example of instances soon.

Ah, it does look like Pixar provides an instanced version of the kitchen set and also a point instancer example. http://graphics.pixar.com/usd/downloads.html

**Comment by jegstad-dwa** [comment] 2020-04-02 19:46
Cool, glad the workaround's working out.

If you want we can continue chatting about instancing via direct email vs. on an issue ticket since we're going off topic a bit. Or we can start another ticket.

**Comment by jegstad-dwa** [comment] 2020-05-13 18:11
@truant-bss @morgan-cg 

This should be resolved in the latest code update.

Please let me know if it's not,
-jonathan

**Closed as completed by jegstad-dwa** 2020-05-13 18:11 UTC
